apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
- deployment.yaml
- service.yaml
 
images:
- name: gitopsbook/sample-app
  newTag: v0.1
EOF

#create .flux.yaml
cat <<EOF > .flux.yaml
version: 1
patchUpdated:
  generators:
  - command: kustomize build .
  patchFile: flux-patch.yaml 
